version: '3.8'
services:
  # npr-audio-scraper:
  #   build: .
  #   volumes:
  #     - .:/workspace:cached
  #   command: sleep infinity

  pgvector-db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
    driver: local
