version: '3.8'
services:
  # npr-audio-scraper:
  #   build: .
  #   volumes:
  #     - .:/workspace:cached
  #   command: sleep infinity
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: email@me.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  pgvector-db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
    driver: local
